version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/:/opt/app

#  frontend:
#    image: node:14
#    working_dir: /app
#    volumes:
#      - ./frontend:/app
#    command: ["yarn", "start"]
#    ports:
#      - "3000:3000"
