[tool.black]
line-length = 90
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"

[tool.aerich]
tortoise_orm = "src.settings.TORTOISE_CONFIG"
location = "./migrations"
src_folder = "./."
